# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89a357f0955e517e853a6f617b73f1970ba56e0025b1744dc89655c0663f311747d14e281839cacc1f1dedb753517766fe80900de6afd0fc1bd25af6ee44bb1d

test:
  secret_key_base: 48d40efd1deba493126ed578cbfbbd6f50b7f355e7bf98c363719a7e1a10608e5126cd7625b46a5fba807c89aae57bf8119db91b8f4396bc89c0cf18f1f2b151

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
